# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore Packages
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Building Solution
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Executing Unit Testing
  inputs:
    command: test
    projects: '**/*UnitTest/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    publishTestResults: true
- task: DotNetCoreCLI@2
  displayName: Executing Integration Tests
  inputs:
    command: test
    projects: '**/*IntegrationTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    publishTestResults: true    

- task: DotNetCoreCLI@2
  displayName: Executing End to End Tests
  inputs:
    command: test
    projects: '**/*EndToEndTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    publishTestResults: true    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
