# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: AppName
    displayName: "Application Name. (e.g.: BlogWebAPI)"
    type: string
    default: BlogWebAPI

steps:
- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'AWS_CONNECTION'
    regionName: 'us-west-1'
    stackName: 'BlogWebApiCqrs'
    templateSource: 'url'
    templateUrl: 'https://cf-templates-14k7ci0m6vv7i-us-west-1.s3.us-west-1.amazonaws.com/2022062owk-template11cxah8l4zmz'
    templateParametersSource: 'inline'
    templateParameters: |
      - ParameterKey: AppName
        ParameterValue: ${{parameters.AppName}}
    logRequest: true
    logResponse: true
